# Generated by Django 5.2.5 on 2025-09-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.businessprofile'),
        ),
    ]
