# Generated by Django 5.2.5 on 2025-09-13 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_profile',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='business_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
